### PR TITLE
Porting for Windows, macOS and CentOS.

### PR DESCRIPTION
**Pull request by ssrlive**
Hi dude, 
I have make some changes to port your code to windows, but it can run and not able get correct result.
can you have a look to make it work?

Don't worry, the modified code can work correctly in the linux environment.

Compile and test
```
cmake . && make
sample/sample -s google.com -p 443 -r / -c /etc/ssl/certs/ca-certificates.crt
```

### CODE REVIEW

**Comment by ssrlive** [comment]
Done

**Comment by ssrlive** [comment]
Hi guys, 

I found that mbedtls itself has problems and basically it's alway fails when downloading binary files.
Requesting the pages of most websites will also fail because the resulting web page data is incomplete.

Do you have any opnion on this issues?

**Comment by ekoby** [comment]
> Hi guys,
> 
> I found that mbedtls itself has problems and basically it's alway fails when downloading binary files.
> Requesting the pages of most websites will also fail because the resulting web page data is incomplete.
> 
> Do you have any opnion on this issues?

more specifics, please? Did it work before you introduced your changes?

**Comment by ssrlive** [comment]
> more specifics, please? Did it work before you introduced your changes?

Yes. I have test the [ssl_client.c](https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/ssl_client2.c) to download file or web page. 
I always get error results.

**Comment by ekoby** [comment]
> > more specifics, please? Did it work before you introduced your changes?
> 
> Yes. I have test the [ssl_client.c](https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/ssl_client2.c) to download file or web page.
> I always get error results.
> This is the test command `programs/ssl/ssl_client2 server_port=443 event=1 read_timeout=10000 auth_mode=optional server_name=www.sina.com.cn request_page=/ `

Not sure what to tell you. we use this library in internal product. not seeing mbedTLS errors (without your changes). I suggest turning on MBEDTLS_DEBUG and see output

**Comment by ssrlive** [comment]
> Not sure what to tell you. we use this library in internal product. not seeing mbedTLS errors (without your changes). I suggest turning on MBEDTLS_DEBUG and see output

Well. I have tested your owned code without my changes. 
I replaced all `google.com` strings to `www.sina.com.cn`, I got the same error: uncompleted page file.
you can try to do it.

**Comment by ssrlive** [comment]
Well. I have find out the issue. 
Please change the line 
https://github.com/ekoby/uv-mbed/blob/master/sample/sample.c#L29
from 
```
} else {
```
to 
```
} else if (nread != 0) {
```
the sample will runs very fine. Done.

**Comment by dovholuk** [comment]
> changes to port your code to wind

What toolchain are you using to build with? Are you using mingw on windows? I have been (on/off) working on getting this to work in visual studio but you don't seem to be using VS/msbuild?

**Comment by ssrlive** [comment]
> > changes to port your code to wind
> 
> What toolchain are you using to build with? Are you using mingw on windows? I have been (on/off) working on getting this to work in visual studio but you don't seem to be using VS/msbuild?

I am using [VS 2010](https://my.visualstudio.com/Downloads?q=visual%20studio%202010&wt.mc_id=o~msft~vscom~older-downloads) only in windows. and using CMake in other platforms, such as Linux, macOS, etc.

**Comment by dovholuk** [comment]
I've used vs 2017 and vs 2019. I ask because for me:
* cmake doesn't produce a visual studio project correctly (using cmake 3.14.3) I needed to add CMAKE_INSTALL_INCLUDEDIR=include to cmake to get it to generate a project
* the build fails on sys/queue.h

can you include the exact cmake version you use as well as the command to generate/build? I'm curious to replicate how it builds for you.

**Comment by ssrlive** [comment]
Use Visual Studio open the `uv-mbed.sln` in the folder `https://github.com/ssrlive/uv-mbed/tree/master/win32` 
I think it is all OK.

**Comment by dovholuk** [comment]
i didn't even notice the win32 folder at first but now I see. I think having a second port like that kinda defeats the purpose of cmake though.  I ended up doing basically the same thing you did by coping queue.h from libbsd and updating the file so that it compiles. The only difference is I started out in cmake so that the VS solution/projec files are created by cmake. 

But - I can confirm things do build on your branch. I also can compile now on windows from my changes (starting with cmake). I'll try putting up a PR along with some .md to help anyone else who tries to build this library...

**Comment by ssrlive** [comment]
I think modify the `CMakeLists.txt` file to fit VS compiler is a easy job for you. ;-)

**Comment by ssrlive** [comment]
Hi @dovholuk 
I have completed the CMake file. and I have make a [PR for mbedTLS](https://github.com/ARMmbed/mbedtls/pull/2652) 

Now, all Windows works done.

**Pull request closed without merging**
